apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP # not be reachable from outside the cluster
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port