apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  type: LoadBalancer # reachable from outside the cluster
  ports:
    - protocol: TCP
      port: 8000 # service port
      targetPort: 8000 # container port