apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port