
version: "3.8"
services:
    mongodb:
        image: 'mongo'
        volumes:
            - data:/data/db
        # environment:
        #     # - MONGO_INITDB_ROOT_USERNAME=root
        #     MONGO_INITDB_ROOT_USERNAME: root
        #     MONGO_INITDB_ROOT_PASSWORD: example

        env_file:
            - ./env/mongo.env
    # backend:
    # frontend:
volumes:
    data: