apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: maksymposkannyi/kub-data-demo:1
          volumeMounts: # mount volume to container
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          # emptyDir: {} # type emptyDir volume
          hostPath: # type hostPath volume
            path: /data/story
            type: DirectoryOrCreate