apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: maksymposkannyi/kub-data-demo:2
          env:
            - name: STORY_FOLDER
              # value: "story"
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts: # mount volume to container
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          # emptyDir: {} # type emptyDir volume
          # hostPath: # type hostPath volume
          #   path: /data/story
          #   type: DirectoryOrCreate
          persistentVolumeClaim: # type persistentVolumeClaim volume
            claimName: host-pvc
