apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: task
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - name: task-api
        image: maksymposkannyi/kub-dep-tasks
        env:
          - name: MONGODB_CONNECTION_URI
            value: 'mongodb+srv://max200pl:29121994mO111@cluster0.1evvjy7.mongodb.net/kub-dep-users?retryWrites=true&w=majority&appName=Cluster0'
          - name: AUTH_API_ADDRESSS
            value: 'auth-service.default:3000'


